services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Redrose4@
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql